{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4ce972fe-8770-47bd-8356-a9e3fc2d6ed7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Aecom\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Aecom\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Beiersdorf\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Beiersdorf\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Beiersdorf\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Circle-K\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\DOW\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\First Group America\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\8_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\FIS\\9_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Ford\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Ford\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Hearst\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Hearst\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Hearst\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Jacobs\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Jacobs\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Jacobs\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Jacobs\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Jacobs\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kaiser\\8_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\10_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\11_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kinder Morgan\\8_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kone\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Kyndryl\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Mars\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\McKesson\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\McKesson\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\McKesson\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Medstar\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Medstar\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\10_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\11_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\12_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\13_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\14_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\15_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\16_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\17_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\18_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\19_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\20_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\21_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\22_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\23_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\24_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\25_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\26_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\27_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\28_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\29_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\30_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\31_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\8_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\My Company View\\9_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Oshkosh\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Pitney Bowes\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Pitney Bowes\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Reyes Holdings\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Reyes Holdings\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Reyes Holdings\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Rollins\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\10_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\11_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\12_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\13_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\14_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\4_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\5_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\6_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\7_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\8_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\RTX\\9_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Salesforce\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Syngenta Crop Protection LLC\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Syngenta Crop Protection LLC\\2_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Syngenta Crop Protection LLC\\3_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Thomson Reuters\\1_Device.csv\n",
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Trandev\\1_Device.csv\n",
      "✅ Files modified today have been processed successfully.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "from datetime import datetime, date\n",
    "\n",
    "folder_path = r\"\\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\"\n",
    "\n",
    "today = date.today()\n",
    "\n",
    "for root, dirs, files in os.walk(folder_path):\n",
    "    for filename in files:\n",
    "        if filename.lower().endswith(\".csv\"):\n",
    "            file_path = os.path.join(root, filename)\n",
    "\n",
    "            # Get modified timestamp\n",
    "            modified_ts = os.path.getmtime(file_path)\n",
    "            modified_date = datetime.fromtimestamp(modified_ts).date()\n",
    "\n",
    "            # Process only if modified today\n",
    "            if modified_date == today:\n",
    "                print(f\"Processing (modified today): {file_path}\")\n",
    "\n",
    "                df = pd.read_csv(file_path, dtype=str, keep_default_na=False)\n",
    "\n",
    "                df = df.replace(\"No Contract\", \"No Date\", regex=False)\n",
    "                df = df.replace(\"No Contract \", \"No Date\", regex=False)\n",
    "\n",
    "                df.to_csv(file_path, index=False)\n",
    "\n",
    "print(\"✅ Files modified today have been processed successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2d096a85-a08c-41f7-87ce-e90137532c50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing (modified today): \\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Test\\1_Device.csv\n",
      "✅ Files modified today have been processed successfully.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "from datetime import datetime, date\n",
    "\n",
    "folder_path = r\"\\\\192.168.200.3\\Centralized Invoice Processing\\Vinay\\Raw Transformation\\Test\"\n",
    "\n",
    "today = date.today()\n",
    "\n",
    "for root, dirs, files in os.walk(folder_path):\n",
    "    for filename in files:\n",
    "        if filename.lower().endswith(\".csv\"):\n",
    "            file_path = os.path.join(root, filename)\n",
    "\n",
    "            # Get modified timestamp\n",
    "            modified_ts = os.path.getmtime(file_path)\n",
    "            modified_date = datetime.fromtimestamp(modified_ts).date()\n",
    "\n",
    "            # Process only if modified today\n",
    "            if modified_date == today:\n",
    "                print(f\"Processing (modified today): {file_path}\")\n",
    "\n",
    "                df = pd.read_csv(file_path, dtype=str, keep_default_na=False)\n",
    "\n",
    "                df = df.replace(\"No Contract\", \"No Date\", regex=False)\n",
    "                df = df.replace(\"No Contract \", \"No Date\", regex=False)\n",
    "\n",
    "                df.to_csv(file_path, index=False)\n",
    "\n",
    "print(\"✅ Files modified today have been processed successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c2bcf7e8-126d-474b-a0ad-b3cb3144c8a0",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (2205563367.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    jupyter nbconvert --to script your_notebook.ipynb\u001b[0m\n\u001b[1;37m            ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "jupyter nbconvert --to script your_notebook.ipynb\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d491a32-0232-42d5-8092-e98b0ae96680",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
